export { default as Contacts } from './Contacts'
export { default as Dashboard } from './Dashboard'
export { default as ErrorPage } from './ErrorPage'
export { default as Events } from './Events'
export { default as Forum } from './Forum'
export { default as News } from './News'
export { default as Home } from './Home'
export { default as HomeLayout } from './HomeLayout'
export { default as ProfileLayout } from './ProfileLayout'
export { default as Publications } from './Publications'
export { default as Ads } from './Ads'
export { default as AdDetailPage } from './AdDetailPage'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as VerifyAccount } from './VerifyAccount'
export { default as Profile } from './Profile'
export { default as PrivacyPolicy } from './PrivacyPolicy'

//IMPORT ADMIN
export { default as DashboardLayout } from './DashboardLayout'
export { default as Admin } from './Admin'
export { default as CreateAdPage } from './CreateAdPage'
export { default as CategoryManager } from './CategoryManager'
export { default as CategoryManager1 } from './CategoryMenager1'
export { default as CategoryDetails } from './CategoryDetails'
